#!/usr/bin/env bash

set -e
RUSTDOCFLAGS="-Dwarnings"
RUSTFLAGS="-Dwarnings"

echo 'skipped for now (CHiPs44)'
exit 0

echo '+cargo +nightly test'
cargo +nightly test

echo '+cargo +nightly test single_thread -- --test-threads=1 --ignored'
cargo +nightly test single_thread -- --test-threads=1 --ignored

echo '+cargo +nightly clippy --all-targets --features serde -- -D warnings'
cargo +nightly clippy --all-targets --features serde

echo '+cargo +nightly doc --features serde -- -D warnings'
cargo +nightly doc --features serde
